### ISSUE TITLE
Build a basic application to merge PDF

### ISSUE THREAD

**Issue by antholol19** [antholol19/PDF_tools_app#1]
# Tasks
Create webpage for the PDF merge option:
- [ ] Add upload button
- [ ] Add navigation tabs for other future pdf tooling features
- [ ] Add styling to the webpage using CSS

Create the flask backend:
- [ ] Render the HTML template
- [ ] Upload html inputs
- [ ] Merge the pdf files using PyPD2 package
- [ ] Add download feature for the merged pdf files
